djangonautic/accounts/urls.py
#from django.urls import path
from django.conf.urls import url,include
from .import views
from django.contrib.auth.views import login,logout

app_name='accounts'
urlpatterns=[
    url(r'^$',views.home,name="home"),
    url(r'^login/$',views.login_view,name="login"),
    url(r'^signup/$',views.signup_view,name="signup"),
    url(r'^logout/$',views.logout_view,name="logout"),
    url(r'^userhome/$',views.userhome_view,name="userhome"),
]

djangonautic/articles/urls.py
from django.conf.urls import url
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import login
app_name='articles' #NoReverseMatch error
urlpatterns = [

    url(r'finalmap/$',views.map,name="finalmap"),
    url(r'settings/$',views.settings_view,name="settings"),
    url(r'locations/$',views.locations_view,name="locations"),
    url(r'contacts/$',views.contacts_view,name="contacts"),
    url(r'deletecontact/(?P<user_id>\d+)/$',views.delete_contact_view,name="delete_contact_view"),
    url(r'deletelocation/(?P<user_id>\d+)/$',views.delete_location_view,name="delete_location_view"),


]

#consists of

urlpatterns += staticfiles_urlpatterns() #check for debug mode and serve static files

djangonautic/djangonautic/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('accounts.urls',namespace="accounts")),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^articles/',include('articles.urls',namespace="articles")),

]

djangonautic/accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

djangonautic/articles/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
#from phonenumber_field.modelfields import PhoneNumberField

class SavedLocations(models.Model):

    username = models.ForeignKey(User,default=None)
    source = models.CharField(max_length=50,null=True)
    destination = models.CharField(max_length=50,null=True)
    def Source(self):
        return self.source
    def Destination(self):
        return self.destination

class UserContacts(models.Model):

    username = models.ForeignKey(User,default=None)
    number = models.CharField(max_length=12,default='None',blank=True) # validators should be a list
    def __unicode__(self):
        return self.number

djangonautic/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegistrationForm(UserCreationForm):
    email=forms.EmailField(required=True)
    class Meta:
        model =User
        fields=('username',
        #'first_name',
        #'last_name',
        'email',
        'password1',
        'password2')
        def save(self, commit=False):
            user=super(RegistrationForm,self).save(commit=False)
            #user.first_name=form.cleaned_data['first_name']
            #user.last_name=form.cleaned_data['last_name']
            user.email=form.cleaned_data['email']

            if commit:
                user.save()
            return user

djangonautic/articles/forms.py
from django import forms
#from . import models
from django.contrib.auth.models import User
from .models import SavedLocations,UserContacts

class SavedLocations(forms.ModelForm):
    class Meta:
        model=SavedLocations
        fields=["username","source","destination"]

class UserContacts(forms.ModelForm):
    class Meta:
        model=UserContacts
        fields=["username","number"]

djangonautic/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout
from django.http import HttpResponse
from django.contrib import messages
from .forms import RegistrationForm

def home(request):
    return render(request,'accounts/homepage.html')

def signup_view(request):

    if request.method=='POST':
        form=RegistrationForm(request.POST)
        if form.is_valid():
            user=form.save()
            login(request,user) #pass the user credentials
            message = messages.success(request,('account saved!'))
            return redirect('accounts:userhome')
    else:
        form=RegistrationForm()
        return render(request,'accounts/signup.html',{'form':form})

def login_view(request):
    if request.method=='POST':
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            #log in the User and display message!
            user=form.get_user() #retrieve the user
            login(request,user) #pass the user credentials
            if 'next' in request.POST:
                return redirect(request.POST.get("next")) #because we have a name of next in that hidden field
            else:
                return redirect('accounts:userhome')
    else:
        form=AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})

def logout_view(request):
    if request.method=='POST':
        logout(request)
        print("logout working !")
        return redirect('accounts:home')

def userhome_view(request):
    return render(request,'accounts/userhomepage.html')

djangonautic/articles/views.py
from __future__ import unicode_literals
from django.shortcuts import render,redirect
from .models import UserContacts,SavedLocations
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from . import forms
from django.contrib.auth.models import User

#from django.views import Views


@login_required(login_url="/accounts/login/")
def map(request):
    if request.method=='POST':
        print(request.POST.get("submit"))
        if request.POST.get("submit")=='save':
            #save the values in db and dislay message
            form=forms.SavedLocations()
            instance=form.save(commit=False)
            instance.username=request.user
            instance.source=request.POST["source"]
            instance.destination=request.POST["destination"]
            instance.save()
            message = messages.success(request,('location saved!'))
            return render(request,'articles/finalmap.html',{'message':message})

        elif request.POST.get("submit")=='calculate':
            return HttpResponse("Calculate the distance and time!")
        else:
            return HttpResponse("Not Working!")
    else:
        return render(request,'articles/finalmap.html')

@login_required(login_url="/accounts/login/")
def settings_view(request):
        return render(request,'articles/settings.html')

def locations_view(request):
        objects=SavedLocations.objects.filter(username=request.user)
        print(objects)
        return render(request,'articles/locations.html',{'locations':objects})

def contacts_view(request):
    #saving the numbers
    if request.method=='POST':
        form=forms.UserContacts()
        instance=form.save(commit=False)
        instance.username=request.user
        instance.number=request.POST['number']
        instance.save()
        message = messages.success(request,('contact saved!'))
        objects=UserContacts.objects.filter(username=request.user)
        print(objects)
        return render(request,'articles/contacts.html',{'contacts':objects},{'message':message})
    else:
        form=forms.UserContacts()
        objects=UserContacts.objects.filter(username=request.user)
        print(objects)
        return render(request,'articles/contacts.html',{'contacts':objects})

def delete_contact_view(request,user_id):
    item=UserContacts.objects.get(pk=user_id)
    print(item)
    item.delete()
    messages.success(request,('number has been deleted!'))
    return redirect('articles:contacts')

def delete_location_view(request,user_id):
    item=SavedLocations.objects.get(pk=user_id)
    print(item)
    item.delete()
    messages.success(request,('location has been deleted!'))
    return redirect('articles:locations')

djangonautic/djangonautic/views.py
from django.http import HttpResponse

#def about(request):

djangonautic/accounts/templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

   {% block head %}
   {% endblock %}

  </head>
  <body>


    {% block content %}
    {% endblock%}
  </body>
</html>

djangonautic/accounts/templates/accounts/homepage.html
{% extends 'accounts/base.html' %}
{% load static %}

<head>
  {% block head %}
    <title>Home Page</title>
  {% endblock %}
</head>

 {% block content %}
    <nav class="navbar navbar-inverse">
 <div class="container-fluid">
   <div class="navbar-header">
     <a class="navbar-brand" href="#">LocationAlarm</a>
   </div>
   <ul class="nav navbar-nav">
     <li class="active"><a href="{% url 'accounts:home' %}">Home</a></li>
   </ul>
   <ul class="nav navbar-nav navbar-right">
     <li><a href="{% url 'accounts:signup' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
     <li><a href="{% url 'accounts:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
   </ul>
 </div>
</nav>

<h2 style="text-align:center">Welcome!</h2>

<div class="" style="text-align:center">
  PUT A SIMPLE MAP(hard code the coordinates of bangalore)
  just to show the user how nice our website actually is ~\(*_*)/~
</div>

 {% endblock %}

djangonautic/accounts/templates/accounts/login.html
<html>
<head>
  {% block head %}
    <title>Login Page</title>
  {% endblock %}
</head>

    <body>
<h1> login</h1>
<form action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}
    {{form}}
    {% if request.GET.next %}
      <input type="hidden" name="next" value="{{request.GET.next}}" />
    {% endif %}
    <!--{{form.as_p}}<br> -->
    <input type="submit" value="login">
</form>
    </body>
</html>

djangonautic/accounts/templates/accounts/logout.html
{% extends 'accounts/base.html' %}

{% block content %}
<h1> logout</h1>
<form action="./login" method="POST">
    {% csrf_token %}
    {{form}}<br>
    <input type="submit" value="login">
</form>

  {% endblock %}

djangonautic/accounts/templates/accounts/signup.html
{% extends 'accounts/base.html' %}
<head>
  {% block head %}
    <title>Signup Page</title>
  {% endblock %}
</head>

    {% block content %}
    <form class="site-form" action={% url 'accounts:signup' %} method="post">
      {% csrf_token %}

      {% for field in form.visible_fields %}
     <div align="center" class="form-group">
       {{ field.label_tag }}
       {{ field }}

     </div>
 {% endfor %}

      <input class="btn btn-primary center-block btn-lg" type="submit" name="submit" value="signup" size="30px">
      </form>

      {% endblock %}

djangonautic/accounts/templates/accounts/userhomepage.html
{% extends 'accounts/base.html' %}

<head>
  {% block head %}
    <title>User Home Page</title>
  {% endblock %}
</head>

 {% block content %}

    <nav class="navbar navbar-inverse">
 <div class="container-fluid">
   <div class="navbar-header">
     <a class="navbar-brand" href="#">LocationAlarm</a>
   </div>
   <ul class="nav navbar-nav">
     <li><a href="{% url 'accounts:home' %}">Home</a></li>
   </ul>
   <ul class="nav navbar-nav navbar-right">
     <li><a href="{% url 'articles:settings' %}"><span class=""></span>settings</a></li>
     <li><a href="{% url 'articles:finalmap' %}"><span class=""></span>map</a></li>
     <!-- only buttons do POST request and for logging out we need a post request-->
     <!-- hence an anchor tag will not work-->
   </ul>
 </div>
</nav>

<h2 style="text-align:center">Welcome,{{request.user}}!</h2>
<!--displaying the success message -->
   {% if messages %}
     {% for variable in messages %}
     <div class="alert alert-success" style="text-align:center">
       <strong>Success!</strong>{{variable}}
     </div>
     {% endfor %}
   {% endif %}
<!-- hiding the message after some time -->
   <script type="text/javascript">
   $(".alert").delay(4000).slideUp(200, function() {
 $(this).alert('close');
   });
   </script>

<div class="" style="text-align:center">

  <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
    {% csrf_token %}
    <button type="submit" name="">LogOut</button>
  </form>
</div>

 {% endblock %}

djangonautic/articles/templates/articles/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
  
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   {% block head %}
   {% endblock%}
  </head>
  <body>

    <nav class="navbar navbar-inverse">
 <div class="container-fluid">
   <div class="navbar-header">
     <a class="navbar-brand" href="#">LocationAlarm</a>
   </div>
   <ul class="nav navbar-nav">
     <li class="active"><a href="{% url 'accounts:userhome' %}">Home</a></li>
   </ul>
   <ul class="nav navbar-nav navbar-right">
     <li><a href="{% url 'articles:settings' %}"><span class=""></span>settings</a></li>
     <li><a href="{% url 'articles:finalmap' %}"><span class=""></span>map</a></li>
     <!-- only buttons do POST request and for logging out we need a post request-->
     <!-- hence an anchor tag will not work-->
   </ul>
 </div>
</nav>

    {% block content %}
    {% endblock%}

    <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
      {% csrf_token %}
      <button type="submit" name="">LogOut</button>
    </form>
  </body>
</html>

djangonautic/articles/templates/articles/contacts.html
{% extends 'articles/base.html' %}

<head>
  {% block head %}
  <title>Contacts</title>
  {% endblock %}
</head>

 {% block content %}
 <!--displaying the success message -->
    {% if messages %}
      {% for variable in messages %}
      <div class="alert alert-success" style="text-align:center">
        <strong>Success!</strong>{{variable}}
      </div>
      {% endfor %}
    {% endif %}
<!-- hiding the message after some time -->
    <script type="text/javascript">
    $(".alert").delay(4000).slideUp(200, function() {
  $(this).alert('close');
    });
    </script>
 contact add form:
 <form class="" action="{% url 'articles:contacts' %}" method="post">
   {% csrf_token %}
  <input type="text" name="number" value="number" />
   <button type="submit" name="submit" value="save">Add Email</button>
 </form>
 Added Emails:

 <table style="width:100%">
   <tr>
     <th>Email</th>
     <th>delete</th>
   </tr>
   {% for contacts in contacts %}
   <tr>
       <td>{{contacts.number}}</td>
       <td><a href="{% url 'articles:delete_contact_view' contacts.id %}">delete</a></td>
   </tr>
      {% endfor %}
 </table>

 {% endblock%}

djangonautic/articles/templates/articles/finalmap.html
{% extends 'articles/base.html' %}

<head>
  {% block head %}
  <title>Finalmap</title>
  {% endblock %}
</head>

 {% block content %}
    yay! final map is here! *_*

    <!--displaying the success message -->
    {% if messages %}
      {% for variable in messages %}
      <div class="alert alert-success" style="text-align:center">
        <strong>Success!</strong>{{variable}}
      </div>
      {% endfor %}
    {% endif %}
<!-- hiding the message after some time -->
    <script type="text/javascript">
    $(".alert").delay(4000).slideUp(200, function() {
  $(this).alert('close');
    });
    </script>

    <!-- enter the values -->

<div class="container">
<div class="row">

<div class="col-md-6">
<form id="form" method="post" action="{% url 'articles:finalmap' %}">
  {% csrf_token %}
<div class="form-group"><label>Origin: </label> <input class="form-control" id="source" placeholder="Enter a location" name="source" /></div>

<div class="form-group"><label>Destination: </label> <input class="form-control" id="destination" placeholder="Enter a location" name="destination" /></div>
<input class="btn btn-primary" type="submit" name="submit" value="calculate" />
<input class="btn btn-primary" type="submit" name="submit" value="save" />
</form></br>


</div>
</div>
</div>
{% endblock%}

djangonautic/articles/templates/articles/locations.html
{% extends 'articles/base.html' %}
<head>
  {% block head %}
  <title>Locations</title>
  {% endblock %}
</head>

 {% block content %}
<div class="" style="text-align:center">Saved Locations</div>

{% if messages %}
  {% for variable in messages %}
  <div class="alert alert-success" style="text-align:center">
    <strong>Success!</strong>{{variable}}
  </div>
  {% endfor %}
{% endif %}

<table  style="width:100%">
  <tr>
    <th>source</th>
    <th>destination</th>
    <th>go to?</th>
    <th>delete</th>
  </tr>
{% for locations in locations %}
  <tr>
    <td>{{locations.source}}</td>
    <td>{{locations.destination}}</td>
    <td>go to</td>
    <td><a href="{% url 'articles:delete_location_view' locations.id %}">delete</a></td>
  </tr>
{% endfor %}
</table>

 {% endblock %}

 <!-- <div>Source:{{object.source}} destination:{{object.destination}}</div>

djangonautic/articles/templates/articles/settings.html
{% extends 'articles/base.html' %}
{% load static from staticfiles %}
<!-- loading the static module for keyword 'static' -->
<head>
  {% block head %}
  <title>Settings</title>
  {% endblock %}
</head>
{% block content %}
#submit the changes made and store them
<form class="" action="{% url 'articles:finalmap' %}" method="post">
{% csrf_token %}
<div class="container-fluid">
  <a href="{% url 'articles:locations' %}">Saved Locations</a></br>
  <a href="#">Reset Alarm</a></i></br>
  <a href="{% url 'articles:contacts' %}">Change Contacts</a></br>
</div>

</form>



{% endblock %}

<!--
    <h1>Settings:</h1>
    <h2 id="haha">huh</h2>
    <div class="articles">
      {% for variable in username %}
        <div class="article">
          <h2><a href="#">{{variable.username}}</a></h2>
          <h2><a href="#">{{variable.email}}</a></h2>
        </div>
      {% endfor %}
    </div>
    <input type="button" name="hello" value="hi" onclick="/map.html" /> -->
  </body>
</html>

djangonautic/djangonautic/templates/djangonautic/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>base html file</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
  <body>
    {% block content %}
    {% endblock%}
  </body>
</html>